PROJ_DIR           ?= ${CURDIR}
PYTHON             ?= python
SPHINXOPTS         ?=
SPHINXBUILD        ?= sphinx-build
SPHINXMULTIVERSION ?= sphinx-multiversion
SOURCEDIR          ?= ${PROJ_DIR}/source
BUILDDIR           ?= ${PROJ_DIR}/build

abspath_py = $(shell $(PYTHON) -c 'import os, sys; print(os.path.abspath(sys.argv[1]))' "$(1)")

ALL_MK := ${SOURCEDIR}/all.mk
ALL    := $(MAKE) -f "${ALL_MK}" SOURCE=${SOURCEDIR}

.EXPORT_ALL_VARIABLES:

NO_CONTENTS_BUILD = true

.PHONY: help contents build html prod clean sourcedir builddir Makefile

help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

contents:
	@$(ALL) build

build: html

html: contents
	@$(SPHINXBUILD) -M html "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
	@touch "$(BUILDDIR)/html/.nojekyll"

prod:
	@NO_CONTENTS_BUILD='' $(SPHINXMULTIVERSION) "$(SOURCEDIR)" "$(BUILDDIR)/html" $(SPHINXOPTS) $(O)
	@cp main_page.html "$(BUILDDIR)/html/index.html"
	@touch "$(BUILDDIR)/html/.nojekyll"

clean:
	@$(ALL) clean
	@$(SPHINXBUILD) -M clean "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

sourcedir:
	@echo $(call abspath_py,${SOURCEDIR})

builddir:
	@echo $(call abspath_py,${BUILDDIR}/html/index.html)
